package wang.angi.sample.mybatis.generator.maven.model;

import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table city
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class City {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: city.id")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: city.name")
    private String name;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: city.state")
    private String state;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: city.country")
    private String country;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: city.created_by")
    private String createdBy;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: city.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: city.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: city.name")
    public String getName() {
        return name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: city.name")
    public void setName(String name) {
        this.name = name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: city.state")
    public String getState() {
        return state;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: city.state")
    public void setState(String state) {
        this.state = state;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: city.country")
    public String getCountry() {
        return country;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: city.country")
    public void setCountry(String country) {
        this.country = country;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: city.created_by")
    public String getCreatedBy() {
        return createdBy;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: city.created_by")
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
}