package wang.angi.sample.mybatis.generator.maven.model;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.id
     *
     * @mbg.generated Fri Jan 12 14:29:50 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.name
     *
     * @mbg.generated Fri Jan 12 14:29:50 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.state
     *
     * @mbg.generated Fri Jan 12 14:29:50 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.country
     *
     * @mbg.generated Fri Jan 12 14:29:50 CST 2018
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.created_by
     *
     * @mbg.generated Fri Jan 12 14:29:50 CST 2018
     */
    private String createdBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.id
     *
     * @return the value of city.id
     *
     * @mbg.generated Fri Jan 12 14:29:50 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.id
     *
     * @param id the value for city.id
     *
     * @mbg.generated Fri Jan 12 14:29:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.name
     *
     * @return the value of city.name
     *
     * @mbg.generated Fri Jan 12 14:29:50 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.name
     *
     * @param name the value for city.name
     *
     * @mbg.generated Fri Jan 12 14:29:50 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.state
     *
     * @return the value of city.state
     *
     * @mbg.generated Fri Jan 12 14:29:50 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.state
     *
     * @param state the value for city.state
     *
     * @mbg.generated Fri Jan 12 14:29:50 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.country
     *
     * @return the value of city.country
     *
     * @mbg.generated Fri Jan 12 14:29:50 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.country
     *
     * @param country the value for city.country
     *
     * @mbg.generated Fri Jan 12 14:29:50 CST 2018
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.created_by
     *
     * @return the value of city.created_by
     *
     * @mbg.generated Fri Jan 12 14:29:50 CST 2018
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.created_by
     *
     * @param createdBy the value for city.created_by
     *
     * @mbg.generated Fri Jan 12 14:29:50 CST 2018
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
}